# Much code was written based off @backwardspy's work on catppuccin/python/.github/workflows/publish.yaml | MIT Copyright (c) 2022 Catppuccin
# it simplfied my old workflow by around 100 lines of code. I am blown away :D
on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.11
                  cache: "pip"
            - uses: abatilo/actions-poetry@v2
              with:
                  poetry-version: 1.4.2
            - run: poetry self add "poetry-dynamic-versioning[plugin]"
            - run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
            - run: poetry build
            - run: poetry publish
